language: node_js
node_js:
- 10
before_script:
- npm install -g gulp-cli gulp@4
script:
- gulp
- npm run coverage
branches:
  only:
  - master
  - develop
cache:
  directories:
  - node_modules
env:
  global:
    secure: OCQWRJjRfhM5rU5bS7I8xhY1kPe45yu3zEapXofoOtTYMcpE6l9t9Oq5mR5TEnRICYNBe1vidYJmYOfRRU9+y4EdbegK4d5fnCr12ZDu5sNcts9/AKrh1dlTiRXdCcFXYA1M6w7VOIpkikHvIoL7nUKotDHd3vacYP8r30rF4YvZZJWwM2iW/Yo5y2ovk42Uz5479b2WOwRBZ3/RRqxyczx9P8+zrp9Wec7nnFfDsAhFtmVjs1fyNbwTc/qSA4gUlJnts82GhrYBpDjQD63XGIztdTBFWafpJrxK5WoPXP2ZHs8L2peIjCVG6G7aEW0NXoJKc8IWnUT8MyCeGy4OWlnapU9IgVU/GiUhCEUotiEarfDFlKFE54BxlDvp52HqvGGVsN6xJPxc3bdwuIZoG+wZoAPQCA4vkeEwNiH0ERUuXervUUnOeFSnEqn1wfvWIN9ZW0h2M1j1H+cYMhhSwOUqSB4SXB8OUuKNxpzpEK2RJ7OtDSBIPwDCIehZxMWR6NBbUid1iBRRhzAbXem78uPJ1mTQ0AcWtprKdOVpGX4Ggic9J86bAgEWbBUZDDTSpdGLZSZAIEkl+HP//F1GlPNHwP+PjUbJ78vAsiit/uvZOfxzkGGuLUfnGgD/N5fhtV8f+pUA8Eww2Juzm1bmVD+K61yTqmEazPxD+ugWGBo=
notifications:
  slack:
    secure: SxTXPmLPQQ6UOJiu+eNWfBGrLHhYfzjjYLHrgRWJPb+VLf7flVgufdqMnsYE1ojL6e9DdDE3Ri2SDiowZITZTPYmCwRjaiylVwALtZTgUO2MFkkJ68rt3ksRbHauG+06vnNgxzf5/5O1d0DOPW7IMJRDW6YhSSmhL6M89XggU+vk4N47/XS5N4hnxrAXx+CYgnDYIR4BJbPOS00asITNmdIwqtXFcVH1Bq/lVoRUuZiAbqaC3LBqdu2EhVjIiC0F+Nhv5X0XgzWpnwA1Y1HGK/OywR59UH16dBU7nAH7iTYNinD4p3ZOiUthP2onU1t/rTvKoJ2/QGRMng+vrtxuTBrSo74lMhkZeAFTKaeSZ9CjiDQwa+WNVf2N7Nek6mS5/M6Yxl7teB5fwF3STDNiUFUh4F49fJIfHRxvlXjooQF5mpE1IM1G9VRTEQFCHuMQSYpTVfRWtgqGwBizQobubJFTexr+O24ocS1sINfR4IlV34yJLhl6aBRHmUKV2zPrICeJOogU1w+qx3DeW5bWjTf6/tTSv/R2B8GNc8u6F+YuOQDDWrleTK77Ik/50hydcSNi7cGGxlg3vjlcgXlFpvPnRFDnH1hVVqnic9TxnJRX2CSQfs5nwCpOJq7tHTe12CeK/taYY+7ycxJtjsvROb2xaWp42t4nrr6PV5nVbHA=
deploy:
- provider: npm
  api_key:
    secure: lWUADDu30V5LTi3y4kHZLE7ft3qtXXxos09sUzdxSwudzkn63Y+1g33SdW+Pe8yHeAZjvGdHMmAx+/UAAZWuU/mBeFOAocYuQIDEJGzqrU6kWdJZzOJ2Eloy7zKx8NWaxSAx6jNpsmhlCT4529hOW0u3JF0cV56xB6RwTOA1JbZGfWdyS/Lq0fqEpqLOUytxrsn3efBUxhyx+ZtLIfnyttI82sNjukjYhEFdV6SgT6SNL1lha5uiuXGZS1Uu2FluJGXikp7Gx9zIBr4orkXsYmSTP4Hz7Axk6Ze9clHXT9ZwLLjIHCz/CAyB1o/UdLTRE26EKeUATTp2lAm+P44QSTx6k0vseh7R6c315LRzQPYDcJLrrv52pENs0ig4YBmAZrvI3wWwAJ4P1Df9U4IqcGly9RQvOL/jgGqh7XDW2VSrzeoTCK1mKCjne4TbbESqiYs9IfESwA9vTyjfs0+T7SqUnd11nOeLyTzthvRrHE7JhjUnBRwYFgYLQRGUYGwPTMiEwNJku0qO2vmxD+LFLqlmwGU/pj2kVtDrDihELkeJeQyOmJ+MHjrzTIb/G8YIaJChJCo3k/rwo7Gwbudu6v9P5NA5MIKRx/25kNCx5+MOtokysV9KEqAKWcHdjwpjmaJh8cOt7ACO6OGK1Gl4m6rFzTUH1MYII+vs1MVjL+g=
  email:
    secure: HMBCZnW40yTRvpLC18raCdnCcfv7/S/bXZQ961i4nGZbUK1qE4aoi5rOmmGK6bDeX758uwfpwqgZRUWGJ7fuxSRvkaLcGFa9iQlOpdEOOxha8n2lkAud8cGUwXYkfBAgSBcb16NgmxvGvKmIIh8lDtw8gXbGukKxrcDurTasjDMABbE8cDStQfneYFnD1zBaIBYysYRNxY887bnCaj7NNj2Z+bhaFIEC7x2MoGJ/yD73+WoulteFJ+ScKMAOd3csXGsyrKcm+f7NITVa0zu2x1SMS2GOtTQ74LbEpvIo2CxMhp1IjT3/3t/fPpCpCcbzKqMmjvHWCnmRB/F6IRTAECFXqgiDussgpU5tukQ0Ra7XeRR33v7CpmaZS9PsERR4FQHHlRvo4YqAZt/W7h5EepB3yiGDfGg8RIOQTsLl+0tqe+gJuIfuypBqYTclgazcBvVKDM/lWW6qg5S7jpnTF+ZojDkZvpp3hS/KV9Y5ON3wmEUTTrBZ02nTDy5IUrGFDfz6bg+0VcI40UT/WQ7eIMR+ey6K4QWGNiJ2WH396e+UO4mtEg/Dx2W89loTv73W6DQjxLBtvFZ86HbStr+gEICTD/j0BGU8ar1Bowqlr0jF/baU6QhYXeclCREw3haVqFjuJ49qCTa5jaZPrNe2G5FJSkkKadb5LM7QpDsLSjg=
  on:
    branch: master
