language: node_js
node_js:
- node
before_script:
- npm install -g gulp-cli
script:
- gulp
- npm run coverage
cache:
  directories:
  - node_modules
env:
  global:
    secure: 0CD/9Yi83IR/7vT//zCRW8F1qP7iRJ8tJkaoHOkzBt4pM2B/89nNTpzKnch/igHYUB9PqoyZj2+XSXbJavh6KALc4HLEH6eu8JvR/1RN96cGuoU542vHmd/0ldzS7cv0vslIJkRv2fNrNtuzNSFQROnDOqUfpbSonnw8hvfauy2iyq7Q1PdqPPygQog/1JxiFlie49FHQXa2m3z8jxUZWTtFqeMXTsksvEY4r+AYp8EMP1bq2IZzkzXkllpS7odJ2JEk+A+BMrZPnpOayFBaGwmdlOU2cqRECNZpgfPLfdsBMhxoefwIXk7dFWAzN1kO18HP6MzlT2l7iAxixrHtFcWuaMC7N+trLcZp+ECJIU4iUlAVO1oF9ysNzo6lm4QZTLvPMwdLpVoi4Rv6zSCpIVqNsMlPd3EvTwqZ2Kvbq2NunDWAIFpzCyXQFiuV5+wGTkPh47s0yoPCetGX3mjvIM3IQLxcTW+oof99J4AeFj78CCM1J+gMppkyeadPIWkHv9GWQSVDM4e/zYAwwPXYFXvspoMrQvR9jlkNGf0Vb6zlVF/u0LhcmysoysBEL/8Co8QAW3MKo0C048VveDsTd/P30w2Bqx1am60+Fp7UVf8tTFeowHTO3tCNVZaPuGxj73IM4I4zQOXHPdkZ3CTTkvAuTt4nJ1qTeSwXofl91qw=
