language: node_js
node_js:
- 10
before_script:
- npm install -g gulp-cli gulp@4
script:
- gulp
- npm run coverage
cache:
  directories:
  - node_modules
env:
  global:
    secure: 0CD/9Yi83IR/7vT//zCRW8F1qP7iRJ8tJkaoHOkzBt4pM2B/89nNTpzKnch/igHYUB9PqoyZj2+XSXbJavh6KALc4HLEH6eu8JvR/1RN96cGuoU542vHmd/0ldzS7cv0vslIJkRv2fNrNtuzNSFQROnDOqUfpbSonnw8hvfauy2iyq7Q1PdqPPygQog/1JxiFlie49FHQXa2m3z8jxUZWTtFqeMXTsksvEY4r+AYp8EMP1bq2IZzkzXkllpS7odJ2JEk+A+BMrZPnpOayFBaGwmdlOU2cqRECNZpgfPLfdsBMhxoefwIXk7dFWAzN1kO18HP6MzlT2l7iAxixrHtFcWuaMC7N+trLcZp+ECJIU4iUlAVO1oF9ysNzo6lm4QZTLvPMwdLpVoi4Rv6zSCpIVqNsMlPd3EvTwqZ2Kvbq2NunDWAIFpzCyXQFiuV5+wGTkPh47s0yoPCetGX3mjvIM3IQLxcTW+oof99J4AeFj78CCM1J+gMppkyeadPIWkHv9GWQSVDM4e/zYAwwPXYFXvspoMrQvR9jlkNGf0Vb6zlVF/u0LhcmysoysBEL/8Co8QAW3MKo0C048VveDsTd/P30w2Bqx1am60+Fp7UVf8tTFeowHTO3tCNVZaPuGxj73IM4I4zQOXHPdkZ3CTTkvAuTt4nJ1qTeSwXofl91qw=
notifications:
  slack:
    secure: Ue7jsRrQvPdhdQoAxSNLCL4AYA4nk8vP1NADOxHiiIvO/M6jamk40fKuw0exfvi9/j3uw32ErI9zAR8qaZhihLVrFZrCKVKF2agruCJil6oMKK1oVBRvSGLaVv0XzrRRoLkVbns6C8CptTxuEuLldLDVjU5h6X+ZqO7lC8uVSjF2zyGmWTL5jKkKwx3635HLd9Sn8iGPTyP/LvLpNz2BfmGkxL2/juXO+kyyZbbWSQ/E2pz2rChNg0ljiKVX8efjp0QR5/1AQ07ks9IRHzzvTpDHvPa3ko8du1ztJnNpoSIBW1+XgqBwA89Nn23Wdl+Ywz0Bo4LSp+Rn7llxPlfTq3JCcDq8jqfe8HQxM576+ZOeSaM+nqiTP0cbhFNOYEcoafD2Lpn/tB94ckUf1Xj/UK2HgBRPtNUBnvEkps/wQA1A6MHJzsnT86Aklx1NvpY7NUR+Ivs/OY/8sd2dnPZlRJZuFW3wXAQrjlcU00o17wh897fVtW2iwXGbEiDdTLnFuEzixts5w3jWKuLws/vfwQkjTkQlrO78w2iusQH4WHDJ1V1LW0Qhz39tsNBsQoQeL5XfpZT1nL3L5Q9uTrTh2oosYMZl730Rowz92p3nY1EBNd+EiG7CCHmZAWzszLUS0QK0npVjaN8reyR0pvAqGj7GhTvuulNO3YDBkPTunhM=
