language: node_js
node_js:
- 10
before_script:
- npm install -g gulp-cli gulp@4
script:
- gulp
- npm run coverage
branches:
  only:
  - master
  - develop
cache:
  directories:
  - node_modules
env:
  global:
    secure: btU56y+z+PF4K3oXdKCnBPgW5QZSCZbhaei51YfM60S9emcBdBlYK+FMEx2LzyfePGP4YSXyNWhjtmv6pXpANFBOTPUy8wix5mEGrhgtpBP2HwV2sPK2nBIefluBHqXVam/EivKyOlD471uGThbyDVbH2+LJF3OL6gtjamvGHWpQLUydW4nWbUsNZP+7zFySKzH6rQ+7ci+NlQj7Z1qhhvlcDrUckytmBBEgHO53Rumz/C+tb5QUT/xiQSgzx6921ctXxHxtCXaTnjxBgQPQ1+6HlxjAIVMRKRKRh14p/xjh2f1lTzom30r03TXk1RNeHovLRSG7MGh83/ccqURXoHJXnfh+Uaobqp2Fo7M7df7i1qB7L/YYS+vPCK3VKxA6drLquaNyF2Zwjl+UGKnF3tv3hcb6FlYnov7bJlRawo4sTxD/9HyTsLYH/TaASunAWBAtx/0DLo7ru8Pjae1GSK3tEbrxAfny+k5d3riJpDwZiEz4/2vBR50gXQKGUJLGQJRbbWJXsXUmlZy0VOIopNXlewXTF8BnCi9ItCpKWUg5lWhb9F77LcjbOo9dauc+FBDGoyzVS7Bkh58a5xWp9TYsRhIHAHdoPp7Ju19O+Q66SyeNbaPEcvPk3NSp7kslCotHtAD5kI2yG0hddm5yOdsaTk59M9Lks+akr8qdA+0=
notifications:
  slack:
    secure: nm9/WxtpGYEFAlCNdMse4SuI7ZK4zIsVS9C44e0HWEKKLDawTN5XXfNCMBFef0LAl5HcsWWpdPFARgTuBIPQZeTUHF62kA9iHqpdNTjS8v9vsaGv3pEZoX18GdrCkBm3RTGCEKzDtd4T4i4qYDBe5bWQ9hJ/en71zsIKW1EzBKaSer25gTL/0GGhHZWT5h9dKdHY7WURTPsFXPAjnnejB/atU0qyLmj3osX5YqOcKUmmovoavulPVYrwK3eofshDVjw0rqv7lpszZwasJ3akCb94AU+geT8oFgKZWeUNyO/z6k7tPDiIMCiqboNFSm9VQX2Rm7czPW+szqOMPkXvoIPHdkX9A3ex15NDHhqtml149kb9nOj0Oz34uEyvK9gMoWGoYwSof9XQqj+vRCjVSOEXCpEKkSXgNYDo9eg6hZIg7cUrfSonca81VfYfRl5GDkfEEqw2ccmPIloaJHLz9DULh0gY6bp/rZ1uSPpn7YE75v5VPa2G52+6jwcIwHlYW8hiurfTZ9d/dwZXSnB66UWYJWdkOwodMcOB3OFcsLTLjC0DxauzD4qQg7NHC1yNyfuDDpc/tK9y3xYjJk4oAtD41J1XZjZsIYZHVO0JteEkgSoMXyalB969/dizn5A/ObAnj4mjFZs3sZKz207WyKIJGc9CK00KOG6KJXZTA4g=
deploy:
- provider: npm
  api_key:
    secure: vr7QaufYDwKqH5CWcU11pPZDiISkBelIPyfzxUW2h5hfIoaXFHhUomnJzB5NJLdj1GKPRmDwFenDDKZ5gsAzKII88X72ZNTJvhhRlqAuGSfDwOjECOSE22dksV3IH/q2782mPIKljO2FwEoYua2Dym4My9X/3XMPIJ5to+Ykfb5n14d4F5ommmqVUjacZBulu/5VBUdCSTNl4QylgZGVcSbLKdT5NcM6ILbp9YHEvvZGALw2rLA79oi4ocPFOJuld9IvhFU9OpwDV+C8CWnw23HIbafn32DknYTGz8ECw1xi6Od8KxzZS1WU++B/mZxwh5kZJAPgfaxGoHLapfndUT5W1/PrNC9ROJTcJLpO7zyj+vAgUSy4rv7iNVScgYwqBwBMQ4TOfTX0whfPimkgtLYquR2AB/4Q08mgSTM8UijanQ9GcKCIL6VnvwpIQ3eMcTf1i0FOvYkXoUVvT+6rOOXVDs/1Rhmrjx7LhLbHE4nZvqmmrc2BCbFaPzV1K8MmXGxJDc2Gu5eBH+9Oz9lJ1lo3OqWDnT4JaZWjvR2S4YtghJll1+FQ/Gh1YgiB2pbhM6KkVz/8MhL18jHjEFlJSfH1mPEmQhU8n62ARjovesOQG9s9C+9gD5w7RQpkgIx/EaB2NulldZzx/nnKCBA3wDkovFBBtz/PVkJa+GdyMqw=
  email:
    secure: g3m02PvgqkP6UjOv1BnyqkdTcJbL8ufuBxHhfHM2y1ElORePHAw9SC8tZeuW67zAXxsXst2JTYnpTyQGzvl7Mm12SgfXm4tDPO4ATxgb6xAjVjJNUV4wVdPdYYTkuJ4ICdgQWX961q2BqBSpm71Nkim0A70WBZHV1TQ4G35RJ94e62z5Sek3T/kHduOxGW0R6wlRE5NEl1aX64QiLxqgtdWcvuVvfRMkD/A+zIcxkGi9wkx8CCFZCNeVNeuSS/W8MMdVU8I7xGi5hN42sCWcpKkDn3t4AURpsYXdgjP3aCCHBsvYHdwCTu+gQjvtWSSPE2/fgWXF9W8F7aVZAcU898YczvN9UVdetf/XUuBhmvz2NHNaU/oNOL4cOxTVj/9TiV17M7RwCQfU9jupmtdm+WR25c4OtOR4vp4L4tAus9RkaRYS88Uo22LqvqDJnTxNwB5lEG13gEzudKxfqKD9/ckgy2tAj/eYxVO2rmEcS9NlRxA19trS/5ReBRylzyjqI3JBNWHMEIrOVl+baO108BV68CZAxOvhLgo3HMd4QIrLXwj+7Td+qXBKItVxdTZmyg5aR2okR0U6uJxORVegod/+bo5NQxQ0zT0XhiHc2PI3ASGVAhlnAbu9zR1lBLFw57oFsaR41eQ2VZezwkK8odALH2MFuKR4nsGqqkEUUYk=
  on:
    branch: master
