language: node_js
node_js:
- 10
before_script:
- npm install -g gulp-cli gulp@4
script:
- gulp
- npm run coverage
cache:
  directories:
  - node_modules
env:
  global:
    secure: SwKdLcwEv7L/pmnPIwXyg6v4ca5rta4ALkHDLnVl2qpDf9N6LZzx8xSabKlfJMT2URvoQ5o/MTGcYnXiij1foJUcMcse3xMvCts59sSBg88C727iRidG2ZUQFhIvvGsTs6rclrJllvnGeO/jd0LSrFNFN60nF5Qk788WxaxpVsBIZV8mS39cniKlw2H2mukOrAdOlH+RJzFPQaKetehoAQ/pDWr3xYco360FxPlyt1kTLwhyQZcIbp68qk+oExQGBtY++hlkGJxZF6rmoeDOe84ISzyoQWQhykvcRdQ1pSo4UFXKrmHFQh5ckifbtn0LJtNwF/VkVjGrUxci86UkiZPbz7yhab9QLh8Ig0bE1M3C4rIHi8gpLGo12BJhlYgmApiaAtXebZdVy21CmxB+psQrrvjRF4EMFDvtL9FhJBzXAC1C8dek8EmRk/xq70qStPG6NmfwENpuedf7aYbu+D7LpJ/Ye0Gux6RNCvWJRIBYo85aAalyBze7tKbma9QQrQ0aE29QTvB7twc9j+NVgTD7/nxF1e+8oZC3fbo9t6ZsRIVpH3M4ZEEDQ2BfTAW1m8ILDXcCbAHzt+U2/PmZJ5CD9gQuwqevXH4/o6mdkYug7d0/m2D31y+GuoYuBK7ArEdeoRAoplcsn48imHhk3TWnZel6BvnIB+UzC00nO1c=
notifications:
  slack:
    secure: tJq+OJ9l0d01UIm1ptj6bJfyoD7NtZVunpdoO3Ribu1MCpMbTpoE2icseCSGAHTxqbaEsDGmI24MwVx+wCpHmqwWEpauC6+SKJ1TFOa+5CFBuuEFLVfAJgF0AjDP/VlSf5oRNN5+15/MDIggGT1rDpOHx0CJgNFo+G4hKDUVYxn29qt9s/0u9RrhYEX4K89ffnT0y1K13iWAiEc60DWtPFdbMpquDq/FvZ0Xg1fXdLiUCngPYvwLf6JlNZaHwkcC1lRzXXVQVZMZ6TA0I4I/moK2sA40A+7G33aIkQEViuAMF1dSrM89lrQovL6ueD5VEmar8qI6FKQmg7jc4eG53V+CdDmzl98VdSQJRnp/IU0NQ/CpJ5stx61u/EBOo2mvY8+0Ffkq6yvrjDuuGVVdvSOaV5NfiKPQGB27AHELq78/KU2nxznR28O2FRNn7tj09HXhnT0Y0o7R6DbEb+NEXdzElSc6FEP0zRXLkNvCXPdd4Ek4XzsQXvkx3b0f32aVOBLIOM/TmSVD6uz6ijgu5u8fJbUTLJANG5lYcfhSi12x76uUaJAUUTisspfQ3QJue/rdDA7wsJ/I//xO7JfBTgqKuNqKNQt+TnUaesRDbKg5B3Tx8mhLlNpkILt1nc/VqSsTHh2KMb/6UzEYCbftwxTfMv3pzZAHJuayX1zlwVg=
deploy:
- provider: npm
  api_key:
    secure: GOkOR5/CYWWc8hoiKnibS60uIayHk1OIVHsplrz3C093rmTmuZJMwL1wXqwayXbxhAfCWUyMaXK9UTjQnEp45kpNlgMY1Y3RVnikk0gWgYoCzMgxNu0adaOT2dzRRxv1MBM/td2B7rHyNXvNxVz9KUKvfKadqc9PlfRPd42VQFgcwlmRhod22vF7PFpOROgAb8HgdVkP3baG4mGlmvZH7JcJeabmDehwJ8270YYYLuYZ70JUND+7B6B8nUv35GMzpxX6UZOjaf/dTdGMIgdCcjAdy6c8DI70W5+xg+FuxKg22YIXCugFYiFeZtfWnWStogIJAH4AjnATXKPwDo4cO6/KyL87Audk7esAy0A3LLVIeqdSCuUaPaiYjwvvy/qjI8l0stO3rq7PUz4CHCi4RUeXb1amDZipMpSwBc/gW4TyJr7zK7vS4XN9Jsp52XUMQx0Twkfc3NEUwgY2k9ExS00MXoWUKgvvxQ3IghZ1fosnrwczBc5IJSv+UU8GooVr/zXSR+j2G6a+9xjTuEP+GhF+OXtSaa2CEDcXSFhQOvfs3+6W4Si20kSjyCIbu/pPugUUnKddugdP/jcBSaHlAetqi9CpFvtEXzrDlIhQ8z4gChUxSNH2jPcmx/8sef/+cQZiEck0txAGHEHrTlsPivSvA1iTK52s6dxnYpIp+bA=
  email:
    secure: c+CJVbp6Js5u4a+eaRpIf3AvOMvO9mWSA29Thoidnx92F7Yyjy17Hvnc1sRQ4g8TPEYuSZgXk1C16B8suwdcAsHh32zvX0Kb5VJtDgGekLyTm6DJqzW0pWY9wjU/sc/RMRzlcJFv0B78H7faS80mzKyGTdw0YOiVfOTjonM6sgVdafPlM+Zk7AIAbJ8Qfb5Qzxx7fnDzkvg9tZvQpFh25OukEXbV4wtTwNo60lvGw7ukWb1vtx4po2DwISsC0hXHFrXKl1NPHWCzAGN1Lzjo0tnntFuj+cVnB2CQv85nGCFviV8z1W19bQ/nb4GMsJE4eRfFFDQeikA5zmgRT5In44N/SexzJ7PARzNNAVZnDsDXIiIxu0uzg9LgZbBlEjvJz8Jg3uX6dzVB4F7YNq+agae4tyNuMrACq2/Dee3f7O229K2WzA1/VWt7TJd6Au0VPL8KfFArn3GOaIifvcq6IGc3kClAT5H0YIce2bwpz2F7dZ60dCQaAaHQ6Wmuozu6XLNB8FRUv5Ktn1puqDUgKjCOKhit7oJ11rRR91p4kxOA0dNkK0UZx76v84144MRSazq2ToMHkQ7LaHgsrqES8nUADS/5sk1EUvGFBDDe/m9jdl7V+RcD522DHxFOnACM/6TdjRoXrLcBCN0ml2K7nCmPnjIg1PpP1UE3a3hULk4=
  on:
    branch: master
